language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - tip

install:
  - go get -v "github.com/golanghr/platform"
  - go get -v "golang.org/x/net/context"
  - go get -v "github.com/coreos/etcd/client"
  - go get -v "github.com/Sirupsen/logrus"
  - go get -v "github.com/smartystreets/goconvey/convey"

script:
  - go test ./... -cover
