language: go

go:
  - 1.4
  - 1.5
  - tip

install:
  - go get -v github.com/nlopes/slack
  - go get -v github.com/Sirupsen/logrus
  - go get -v github.com/gengo/grpc-gateway/...
  - go get -v github.com/golang/glog
  - go get -v github.com/golang/protobuf/...
  - go get -v github.com/golanghr/platform/...
  - go get -v github.com/golanghr/slack
  - go get -v google.golang.org/grpc

script:
  - go test
